# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c903186c5ebb34ec190fdcb1d393b4ae9a4d5fb93498d496c73a1cbb9af46c2fef09ebd61a676ba0989046874b37568481e909860d49881af8d4acb64b963f49

test:
  secret_key_base: c77a91312bbd982bd819385573fea16b91c07cee96d961db80e2614d2f483eba5aa47328460cd6b26de27c329a6c34771dfed378aad58eca4f2b89f2cde71b38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
